namespace SolarisRec.Core.Card.Enums
{
    public enum CardId
    {
        #region SoItBegins

        //Belt
        Turncoat = 1,
        InsuredColleague = 2,
        BeggarInformator = 3,
        KoronisBelter = 4,
        Concubine = 5,
        MadameKyung = 6,
        Phisher = 7,
        VestaExtortionist = 8,
        YoungScum = 9,
        VestaThug = 10,
        RebelSaboteur = 11,
        GangLeader = 12,
        MrYue = 13,
        GrowingInfection = 14,
        Execution = 15,
        HuntDown = 16,
        OrganDonor = 17,
        YouareTired = 18,
        EyeforanEye = 19,
        Arson = 20,
        BestoftheBelt = 21,
        Donorcenter = 22,
        AsteroidIntelStation = 23,

        //Earth
        AcolyteinTraining = 24,
        MonkofSol = 25,
        SanctionedPriest = 26,
        EarthseedActivist = 27,
        PeacefulRepresentative = 28,
        ReveredMediator = 29,
        NegotiatorEld = 30,
        ExiledPaladin = 31,
        InvestigatorPaladin = 32,
        GuardianPaladin = 33,
        PoliticalAdvisor = 34,
        CosmicLinkManager = 35,
        AmbassadorSunders = 36,
        HeroicRescue = 37,
        SawitComing = 38,
        ExpendableBodyguard = 39,
        IntroducingtoTheFaith = 40,
        CantTouchMe = 41,
        HardTimes = 42,
        TwistofFate = 43,
        ScorchedEarthTactic = 44,
        PoliticalDelegation = 45,
        PoliticalAcademy = 46,

        //Mars
        MartianDiplomat = 47,
        CrimsonGrenadier = 48,
        CrimsonLegionInfantry = 49,
        SpecialOps = 50,
        CrimsonShockTroops = 51,
        CrimsonLegionScout = 52,
        SergeantJoseph = 53,
        ChefuMilitia = 54,
        TarakanGuard = 55,
        ChameleonCorps = 56,
        ExplosiveExpert = 57,
        SupplyLineOfficer = 58,
        IrharenVeteran = 59,
        GeneralRwanda = 60,
        Headshot = 61,
        PreparedAmbush = 62,
        UnexpectedCourage = 63,
        DevotedLearning = 64,
        MartianEducation = 65,
        Aftermath = 66,
        ChemicalWarfare = 67,
        WarPropaganda = 68,
        OlympusUniversity = 69,

        //Mercury
        MercurianRecruiter = 70,
        ApollodorusMerc = 71,
        NewDallasSapper = 72,
        SecondGenColonist = 73,
        NoahtheArchitect = 74,
        MiningBeliever = 75,
        NewDallasOpportunist = 76,
        CalorisBasinTrader = 77,
        AMU = 78,
        OutcastSmuggler = 79,
        MiningWalker = 80,
        BobbyMcKendrickTheBoss = 81,
        CombatSteroids = 82,
        GiveUporGetUp = 83,
        MercifulLoan = 84,
        NabuInsurancePolicy = 85,
        InvestmentintheFuture = 86,
        RecycleEverythingthatShines = 87,
        PlannedDemolition = 88,
        BadQualityFuelCells = 89,
        CalorStorage = 90,
        ApollodorusDock = 91,
        WalkingFactory = 92,
        GearingStation = 93,

        //Titan
        DataMiner = 94,
        OrdinaryServitor = 95,
        SinlapParasyte = 96,
        OracleDroid = 97,
        EbonyFranth = 98,
        BattleDroid = 99,
        LigeiaDeveloper = 100,
        XanaduLeadLibrarian = 101,
        LazarusProtocol = 102,
        CyborgBodyguard = 103,
        BhavyaAdministrator = 104,
        IllusionalDistraction = 105,
        FatigueoftheFlesh = 106,
        InterplanetaryAssist = 107,
        SuddenTurnaround = 108,
        SilenceYourMind = 109,
        DataBreach = 110,
        MindOverride = 111,
        WipetheMind = 112,
        SearchingtheArchives = 113,
        AncientDrives = 114,
        DataMine = 115,
        XanaduMemoryVault = 116,
        CyberBankOfTitan = 117,

        //Venus
        DisguisedCrew = 118,
        DustAddict = 119,
        DisciplineofNight = 120,
        EvidenceAnalyst = 121,
        QuasimDaher = 122,
        IshtarAssociate = 123,
        TravelingMerchant = 124,
        HiddenCell = 125,
        MaatMonsSupervisor = 126,
        FailedExperiment = 127,
        Mole = 128,
        FamedNavigator = 129,
        VioletThorn = 130,
        UnexpectedExpenses = 131,
        FailedProject = 132,
        ActofAggression = 133,
        ForgedTravelLog = 134,
        IntelGathering = 135,
        ToxicBlood = 136,
        HologramTrick = 137,
        ImOutofHere = 138,
        Misinformation = 139,
        InfiltrationAcademy = 140,
        TheShadowDistrict = 141,

        //Mission
        ReconIntel = 142,
        Deconstruction = 143,
        MissionSwap = 144,
        IndustrialSabotage = 145,
        PeaceAgreement = 146,
        CollapsingStocks = 147,
        ServerOverload = 148,
        Framing = 149,
        Wiretapping = 150,
        CarefulPlanning = 151,
        ResourceOperation = 152,
        MyWay = 153,
        CallinginFavors = 154,
        LevelthePlayingField = 155,
        Mustering = 156,
        Seduction = 157,
        WithdrawFunds = 158,
        Redistribution = 159,
        SearchforLostKnowledge = 160,
        PlanetaryPolitics = 161

        #endregion
    }
}